In [11]:
x =2
if(x==1:
      print("one")
   else print("two")

SyntaxError: invalid syntax (3381103322.py, line 2)

SyntaxError: invalid syntax (3381103322.py, line 2)

In [ ]:
#loops
i =1
while i<=5:
     print("alfred",i)
     i =i+1

In [16]:
x = ['navin',65,5.5]

for i in x:
    print(i)

navin
65
5.5
navin
65
5.5


In [15]:
av = 5
x = int(input("how many gifts do you want?"))
i = 1
while i<=x:

  if i>av:
     break
        
    print("candy")
    i+=1
    
print("bye")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [13]:
for i in range(1,10):
    print i

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (3025391082.py, line 2)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (3025391082.py, line 2)

In [12]:
for i in range(5):
    if i ==3:
        break
    print("hello",i)

hello 0
hello 1
hello 2
hello 0
hello 1
hello 2


In [19]:
nums =[12,15,18,21,26]
 for num in nums:
     
      if num \ 5 == 0:
         
        print(num)

IndentationError: unexpected indent (2910174187.py, line 2)

IndentationError: unexpected indent (2910174187.py, line 2)

In [22]:
num = 7
for i in range (2,num):
    if num & i == 0:
        print("not prime")
        break

In [29]:
#variables in python
a = 50
a
type(a)

int

int

In [30]:
(x,y,z) = 50, 2.4,"python"

In [26]:
type(z)

str

str

In [28]:
x=y=z=10


In [32]:
_dog ="puppy"
_dog

'puppy'

'puppy'

In [33]:
result = 100//40
result

2

2

In [34]:
cars = "bmw","ferrari","fiat"
cars

('bmw', 'ferrari', 'fiat')

('bmw', 'ferrari', 'fiat')

In [39]:
x,y,z =cars
xyz

('bmw', 'ferrari', 'fiat')

('bmw', 'ferrari', 'fiat')

In [36]:
x

50

50

In [37]:
y

2.4

2.4

In [38]:
z

'python'

'python'

In [40]:
x

'bmw'

'bmw'

In [41]:
y

'ferrari'

'ferrari'

In [42]:
z

'fiat'

'fiat'

In [43]:
#number objects
num = 2
type(num)


int

int

In [44]:
num =2.9
type(num)

float

float

In [45]:
2**4

16

16

In [46]:
2^4

6

6

In [47]:
import math
math.pi

3.141592653589793

3.141592653589793

In [48]:
math.e

2.718281828459045

2.718281828459045

In [50]:
2*4

8

8

In [55]:
a ="india"
a =[-2]

In [59]:
a.replace('in','bn')


AttributeError: 'list' object has no attribute 'replace'

AttributeError: 'list' object has no attribute 'replace'

In [60]:
dict1 ={1:'tiger',2: 'lion',3: 'mouse'}
print(dict1)

{1: 'tiger', 2: 'lion', 3: 'mouse'}
{1: 'tiger', 2: 'lion', 3: 'mouse'}


In [61]:
dict1.keys()

dict_keys([1, 2, 3])

dict_keys([1, 2, 3])

In [62]:
dict1.values()

dict_values(['tiger', 'lion', 'mouse'])

dict_values(['tiger', 'lion', 'mouse'])

In [63]:
dict1[4] ='cat'
dict1

{1: 'tiger', 2: 'lion', 3: 'mouse', 4: 'cat'}

{1: 'tiger', 2: 'lion', 3: 'mouse', 4: 'cat'}

In [65]:
t1=(1,2,3,4)
t2=(5,6,7)
t=t1+t2
print(t)

(1, 2, 3, 4, 5, 6, 7)
(1, 2, 3, 4, 5, 6, 7)


In [1]:
 S = set('INDIA')
S1 = set(['U','S','A'])
S,S1

({'A', 'D', 'I', 'N'}, {'A', 'S', 'U'})

In [2]:
S&S1

{'A'}

In [3]:
S|S1

{'A', 'D', 'I', 'N', 'S', 'U'}

In [4]:
S-S1

{'D', 'I', 'N'}

In [5]:
A = 3
B = 4.5
C =A + B
C

7.5

In [7]:
type(C)

float

In [8]:
a =5
b= 3.5
c = a + int(b)
c

8

In [9]:
s = "alfred"
l1 = list(s)
l1

['a', 'l', 'f', 'r', 'e', 'd']

In [10]:
type(l1)

list

In [11]:
t = ("alfred","hudah","josephine")
l2=list(t)
t

('alfred', 'hudah', 'josephine')

In [15]:
type(t)
type(l2)

list

In [17]:
n1= 76
chr(n1)

'L'

In [19]:
dict1 ={ 1:['2','3'],2:['4','6']}
print(dict1)


{1: ['2', '3'], 2: ['4', '6']}


NameError: name 'pd' is not defined

In [22]:
dict1.keys()

dict_keys([1, 2])

In [23]:
dict1.values()

dict_values([['2', '3'], ['4', '6']])

In [27]:
#from csv file
df1 = pd.read_csv("E:\Copy of owid-covid-data ")
df1

NameError: name 'pd' is not defined

In [29]:
#numbers in python
num = 6j+8
type(num)

complex

In [30]:
num.real

8.0

In [31]:
num.imag

6.0

In [32]:
g = 1 +5j
h = 2 +3j
k = g/h
k

(1.307692307692308+0.5384615384615384j)

In [33]:
#binary, hexadecimal, octal
bin(12)

'0b1100'

In [34]:
hex(10)

'0xa'

In [41]:
print(1/(1,3))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [42]:
import math
print(math.exp(10))

22026.465794806718


In [43]:
print(math.factorial(6))

720


In [44]:
print(math.sqrt(25))

5.0


In [45]:
max(1,23,41,13,23)

41

In [47]:
min(2,12,3,1,0.3)

0.3

In [48]:
print(math.pow(2,6))

64.0


In [49]:
#trig functions
print(math.cos(30))

0.15425144988758405


In [50]:
print(math.sin(60))

-0.3048106211022167


In [51]:
print(math.tan(45))

1.6197751905438615


In [52]:
print(math.tan(90))

-1.995200412208242


In [53]:
print(math.cos(60))

-0.9524129804151563


In [57]:
print(math.sin(120))

0.5806111842123143


In [60]:
from array import *

vals = array('i',[5,9,8,4,2])
print(vals)

array('i', [5, 9, 8, 4, 2])


In [61]:
for e in vals:
    print(e)

5
9
8
4
2


###### from array import *
arr = array('i',[])
n = int(input("enter the length of the array"))

for i in range(5):
    x = int(input("enter the next value"))
    arr.append(x)
print(arr)

val = int(input("enter the value for search"))
for e in arr:
    if e**val:
        print(k)
        break
        
    k<=1
        

In [66]:
from array import *
arr = array('i',[])
n = int(input("enter the length of the array"))

for i in range(5):
    x = int(input("enter the next value"))
    arr.append(x)
print(arr)

enter the length of the array7
enter the next value23
enter the next value67
enter the next value78
enter the next value86
enter the next value90
array('i', [23, 67, 78, 86, 90])


In [71]:
from numpy import *
arr = array('i',[1,2,3,4])
prnt(arr)

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [72]:
from numpy import *
arr = array([1,2,3,4,5,0])
print(arr)

[1 2 3 4 5 0]


In [73]:
arr = linspace(0,15)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [74]:
from numpy import *
arr1 = array([1,2,3,45,])
arr2 = array([23,4,6,7,8])
print(min(arr1))

1


In [76]:
print(max(arr1))

45


In [84]:
arr2 = array([23,4,5,6,7,8])
print(concatenate('arr1','arr2'))

TypeError: 'str' object cannot be interpreted as an integer

In [81]:
from numpy import *
arr1 = array([
                [1,2,3,4],
                [5,6,7,8]
    
            ])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
print(arr1.size)

8


In [88]:

m = matrix(arr1)
print(m)

[[1 2 3 4]
 [5 6 7 8]]


In [89]:
m1 =matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 5; 2 6 7')
m3 = m1 * m2
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]


In [92]:
def greet():
    print("hello")
    print("good morning")

greet()

hello
good morning


In [94]:
def add(x,y):
    c = x+y
    d = x-y
    return c,d
    print(c,d)
add(5,4)

(9, 1)

In [1]:
X =4
Y =6
Z = X-Y
print(Z)

-2


In [2]:
def update(x):
    x =8
    print(x)

In [4]:
def add(a,b):
    c = a+b
    print(c)
    
add(5,6)

11


In [9]:
 def person(name,age):
        print(name)
        print(age)
        
person(18,'navin')

navin
18


In [10]:
def sum(a,b):
    c = a+b
    print(c)
sum(5,4)

9


In [12]:
def sum(*b):
    c = 0
    
    for i in b:
        c = c+1
        
    print(c)
    
sum(5,6,34,67)
        

4


In [20]:
def person(name, **data):
    print(name)

    for i,j in data.items():
        print(i,j)
    
    
person('alfred', age=23, city="kampala", tel=760670402)

alfred
age 23
city kampala
tel 760670402


In [22]:
def count(list):
    even = 0
    odd = 0

list =[20,35,68,35,67,90,21,44]
even, odd = count(list)
 print(even)
   print(odd)

IndentationError: unexpected indent (3942495748.py, line 7)

In [28]:


def fib(n):
    
    a = 0
    b = 1
    
    if n == 1:
         print(a)
        
    else:
        print(a)
        print(b)
    print(0)
    print(1)
    
    for i in range(2,n):
        c = a + b
        a = b
        b = c
        print(a+b)


fib(10)

0
1
0
1
2
3
5
8
13
21
34
55


In [30]:
#factorial
def fact(n):
    
    f = 1
    
    
    
    for i in range(1,n+1):
         f = f*1


x = 4

result = fact(x)

print(result)

None


In [37]:
#recurssion
import sys
sys.setrecursionlimit(2000)

print(sys.getrecursionlimit())
i = 0
def greet():
    global i
    i+=1
    print("hello",1)
    
    
    
greet()
    

2000
hello 1


In [1]:
#getting factorial
def fact(n):
    if n==0:
        return 1
    return n * fact(n-1)



result = fact(5)

print(result)

120


In [2]:
#square
def square(a):
    return a*a

result = square(5)

print(result)

25


In [5]:
#anonymous function
f = lambda a: a*a

result = f(5)

print(result)

25


In [7]:

def is_even(n):
    return n%2==0
nums =[3,2,4,6,7,9,8]

evens = list(filter(is_even,nums))

print(evens)

[2, 4, 6, 8]


In [8]:
#anonymous
nums =[3,2,4,6,7,9,8]

evens = list(filter(lambda n : n%2==0,nums))

print(evens)

[2, 4, 6, 8]


In [9]:
def div(a,b):
    return(a/b)
div(4,2)

2.0

In [11]:
#decorators
def div(a,b):
    return(a/b)
def smart_div(func):
    
    def inner(a,b):
        if a<b:
            a,b = b,a
        return func(a,b)
div(2,4)

0.5

In [13]:

print("hello" ,"_name_")

hello _name_


In [14]:
def fun1():
    print("from fun1")
    
def fun2():
    print("from fun2")
    
def main():
    fun1()
    fun2()
    
main()

from fun1
from fun2


In [17]:
class computer:
    
    def config(self):
        print("i5,16gb,1TB")
        
a = '8'
print(type(a))

com1 = computer()

print(type(com1))

<class 'str'>
<class '__main__.computer'>


In [19]:
class computer:
    
    def config(self):
        print("i5,16gb,1TB")
        
com1 = computer()
com2 = computer()

com1.config()
com2.config()

i5,16gb,1TB
i5,16gb,1TB


In [2]:
class computer:
    def _init_(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram
    
    def config(self):
        print("config is ", self.cpu,self.ram)
        
com1 = computer('i5',16)
com2 = computer('ryzen 3',8)

com1.config()
com2.config()

TypeError: computer() takes no arguments

In [1]:
class computer:
    
    def _init_(self):
        print("in init")
    
    def config(self):
        print("i5,16gb,1TB")
        
com1 = computer()
com2 = computer()

com1.config()
com2.config()

i5,16gb,1TB
i5,16gb,1TB


In [3]:
class computer:
    pass


c1 = computer()
c2 = computer

print(id(c1))
print(id(c2))

1622995519184
1622977387424


In [7]:
class computer:
    
    def _init_(self):
        self.name = "alfred"
        self.age = 23


c1 = computer()
c2 = computer()

c1.name = "alfred"
c1.age = 23
print(c1)
print(c2)

In [12]:
class car:
    
    
    def _init_(self,mil,com):
        self.mil = 10
        self.com = "BMW"
        
        
c1 = car()
c2 = car()

print(c1.com , c1.mil)
print(c2.com , c2.mil)

AttributeError: 'car' object has no attribute 'com'

In [18]:
class student:
    
    school = 'telusko'
    
    def _init_ (self,n1,n2,n3):
        self.n1 = n1
        self.n2 = n2
        self.n3 = n3
        
    def avg(self):
        return(self.n1 + self.n2 + self.n3)/3
    
n1 = [45,24,67,56,86]       
        
s1 = student() 
s2 = student()

print(n1)

[45, 24, 67, 56, 86]


In [26]:
class Student:
    
    def _init_(self,name,rollno):
        self.name = name
        self.rollno = rollno
        
        

s1 = Student('alfred',2)
s2 = Student('john',3)

print(s1.name, s1.rollno)


TypeError: Student() takes no arguments

In [30]:
class A:
    def feature1(self):
        print("feature 1 working")
        
        
    def feature2(self):
        print("feature 2 working")
        
class B:
    def feature3(self):
        print("feature 3 working")
        
        
    def feature4(self):
        print("feature 4 working")        
        
a1 = A()

a1.feature1()
a1.feature2()


feature 1 working
feature 2 working


In [1]:
x = 5
x ='alfred'
type(x)

str

In [2]:
class pycharm:
    
    def execute(self):
        print("compiling")
        print("running")
        
class myeditors:
    
    def execute(self):
        print("spell check")
        print("convention check")
        
        

In [3]:
a = 5
b = 6

print(a+b)

print(int._add_(a,b))

11


AttributeError: type object 'int' has no attribute '_add_'

In [6]:
class student:
    
    def _init_(self,m1,m2):
        self.m1 = m1
        self.m2 = m2
     
    def _add_(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student(m1,m2)
        
        return s3
    
s1=[58,67]  
s2 =[45,78]
        
    

s3 = s1+s2

print(s3)



[58, 67, 45, 78]


In [7]:
nums =[4,5,6,7,8]
for i in nums:
    print(i)



4
5
6
7
8


In [8]:
nums =[4,5,6,7,8]

it = iter(nums)

print(it._next_())

AttributeError: 'list_iterator' object has no attribute '_next_'

In [14]:
def topten():
    yield 1
    yield 2
    yield 3
    yield 4
    
    
    
    
values = topten()

for i in values:
       print(i)

1
2
3
4


In [18]:
#errors
a = 5
b = 0

try:
    print(a/b)
    
except Exception as e:
    print("hey, you cannot divide a number by zero",e)
    
print("bye")

hey, you cannot divide a number by zero division by zero
bye


In [5]:
from threading import *

class hello():
    def run(self):
        for i in range(500):
            print("hello")
            
            
class hi():
    def run(self):
        for i in range(500):
            print("hi")
            
            
t1 = hello()
t2 = hi()

t1.run()
t2.run()

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hell

In [1]:
#sorting
def sort(nums):
    for i in range(len(nums)-1,0,-1):
        for j in range(i):
            if nums[j]>nums[j+1]:
                temp = nums[j]
                nums[j] = nums[j+1]
                nums[j+1] = temp
                            
nums = [5,3,8,6,7,2]
sort(nums)


print(nums)

[2, 3, 5, 6, 7, 8]


In [3]:
def sort(nums):
    for i in range(5):
        minpos = i
        for j in range(i,6):
            if nums[j] < nums[minpos]:
                minpos = j
                
        temp = nums[i]
        nums[i] = nums[minpos]
        nums[minpos] = temp
        
                            
nums = [5,3,8,6,7,2]
sort(nums)


print(nums)

[2, 3, 5, 6, 7, 8]


In [3]:
def print_alfred():
    text = "Alfred is a great programmer"
    print(text)
    print(text)
    print(text)
    
print_alfred()
print_alfred()
print_alfred()

Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer
Alfred is a great programmer


In [5]:
def school_age_calculator(age,name):
    if age < 5:
        print("enjoy the time!", name, "is only", age)
    elif age == 5:
        print("enjoy kindergarten", name)
    else:
        print("they grow up so fast!")
        
school_age_calculator(10,"alfred")

they grow up so fast!


In [7]:
def add_ten_to_age(age):
    new_age = age + 10
    return new_age

how_old_will_i_be = add_ten_to_age(7)
print(how_old_will_i_be)

17


In [8]:
name = input('what is your name')
print("hello" + name)

what is your namealfred
helloalfred


In [12]:
birth_year = input("enter your birth_year")
age = 2023 - int(birth_year)
print(age)

enter your birth_year1999
24


In [13]:
weight = int(input("weight:"))
unit = input("(K)g or (L)bs:")
if unit.upper() == "K":
    converted = weight / 0.45
    print("weight in Lbs: " + str(converted))
else:
    converted = weight * 0.45
    print("weight in Kgs: " + str(converted))


weight:76
(K)g or (L)bs:k
weight in Lbs: 168.88888888888889


In [2]:
is_hot = True

if is_hot:
    print("it's a hot day")
    print("drink plenty of water")
else:
    print("it's a cold day")
    print("wear warm clothes")

it's a hot day
drink plenty of water


In [5]:
has_high_income = True
has_good_credit = False

if has_high_income or has_good_credit:
    print('eligible for loan')


eligible for loan


In [8]:
temperature = 30
if temperature == 30:
    print("it's a hot day")
else:
    print("it's not a hot day")

it's a hot day


In [12]:
name = "alfred"

if len(name) < 3:
    print("name must be atleast 3 characters")
elif len(name) > 50:
    print("name must be less than 30 characters")
else:
    print("press continue")


name must be less than 30 characters


In [14]:
i = 1
while i <= 5:
    print(i)
    i = i + 1

1
2
3
4
5


In [18]:
secret_number = 9
guess_count = 0
guess_limit = 3
while guess_count < guess_limit:
    guess = int(input('guess:'))
    guess_count += 1
    if guess == secret_number:
        print('you won')
        break
else:
    print("sorry you lost!")
    
    

guess:1
guess:9
you won


In [22]:
command = ""
started = False
while True:
    command = input("> ").lower()
    if command  == "start":
        if started:
            print("car is already started")
        else:
            started = True
        print("car started...")
    elif command == 'stop':
        if not started:
            print("car is already stopped!")
        else:
            started = False
        print("car stopped.")
    elif command == "help":
        print("""
start - to startthe car
stop - to stop the car
quit - to quit
             """)
    elif command == "quit":
        break
    else:
        print("soryy i don't get you")
        
    
    



> help

start - to startthe car
stop - to stop the car
quit - to quit
             
> quit


In [20]:
for x in range(4):
    for y in range(3):
        print(f'({x},{y})')

(0,0)
(0,1)
(0,2)
(1,0)
(1,1)
(1,2)
(2,0)
(2,1)
(2,2)
(3,0)
(3,1)
(3,2)


In [25]:
numbers = [5,2,5,2,2]
for x_count in numbers:
    output = ''
    for count in range(x_count):
        output += 'x'
        print(output)
        

x
xx
xxx
xxxx
xxxxx
x
xx
x
xx
xxx
xxxx
xxxxx
x
xx
x
xx


In [30]:
import mysql.connector

mydb = mysql.connector.connect(host= "localhoast",user="MBOGO ANGEL ALFRED",passwd ="234")


ModuleNotFoundError: No module named 'mysql'

In [4]:
import mysql.connector
mydb = mysql.connector.connect(host= "localhost",user="MBOGO ANGEL ALFRED",passwd ="234")


NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported

In [5]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [3]:
conda install -c anaconda mysql-connector-py



Note: you may need to restart the kernel to use updated packages.


usage: conda-script.py [-h] [--no-plugins] [-V] COMMAND ...
conda-script.py: error: unrecognized arguments: mysql.connector.py


In [1]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [3]:
import mysql.connector
from mysql.connector import error
import pandas as pd


ImportError: cannot import name 'error' from 'mysql.connector' (C:\Users\MBOGO ANGEL ALFRED\ANACONDA\Lib\site-packages\mysql\connector\__init__.py)

In [ ]:
import mysql.connector

mydb = mysql.connector.connect(host= "localhoast",user="MBOGO ANGEL ALFRED",passwd ="234")