In [1]:
import numpy as np

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
print(arr1.shape)

(3,)


In [4]:
print(arr1[2])

3


In [5]:
arr1[2]=5
arr1

array([1, 2, 5])

In [6]:
arr2 = np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
arr2[1][2]

5

In [8]:
print(arr2.shape)

(2, 3)


In [9]:
arr2[1,2]

5

In [10]:
arr2[1][-2]

4

In [11]:
arrS = np.array(['China', 'India', 'USA', 'Mexico'])
arrS

array(['China', 'India', 'USA', 'Mexico'], dtype='<U6')

In [13]:
arrR = np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arrL = np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
arr = np.random.rand(10)
arr

array([0.19004274, 0.29273249, 0.77854657, 0.54058796, 0.1656789 ,
       0.20135369, 0.30345437, 0.79447679, 0.39783274, 0.28256149])

In [16]:
arr = np.random.rand(3,4)
arr

array([[0.33214173, 0.08502107, 0.30539746, 0.29611573],
       [0.95560212, 0.05024292, 0.53060009, 0.96298352],
       [0.10185039, 0.36878395, 0.68053735, 0.38932182]])

In [17]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [20]:
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [21]:
identify_matrix = np.eye(3)
identify_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [23]:
arr = np.random.rand(5,5)
arr

array([[0.43399678, 0.58672569, 0.08744766, 0.87590884, 0.06218873],
       [0.12458303, 0.9321369 , 0.38942429, 0.64945649, 0.09109793],
       [0.17488488, 0.56287209, 0.98005619, 0.32065206, 0.81314235],
       [0.4948978 , 0.28455027, 0.92419923, 0.21764139, 0.77810004],
       [0.90464081, 0.8330377 , 0.93473464, 0.72737853, 0.5403041 ]])

In [24]:
np.diag(arr)

array([0.43399678, 0.9321369 , 0.98005619, 0.21764139, 0.5403041 ])

In [25]:
arr.ndim

2

In [26]:
arr.size

25

In [27]:
arr.shape

(5, 5)

In [29]:
np.random.randint(-10, 10, 3)

array([ 9,  5, -6])

In [30]:
arr/2

array([[0.21699839, 0.29336284, 0.04372383, 0.43795442, 0.03109436],
       [0.06229151, 0.46606845, 0.19471214, 0.32472824, 0.04554896],
       [0.08744244, 0.28143604, 0.4900281 , 0.16032603, 0.40657117],
       [0.2474489 , 0.14227513, 0.46209961, 0.10882069, 0.38905002],
       [0.45232041, 0.41651885, 0.46736732, 0.36368927, 0.27015205]])

In [31]:
np.exp(arr)

array([[1.5434139 , 1.79809126, 1.09138514, 2.40105648, 1.06416316],
       [1.13267606, 2.53993097, 1.47613072, 1.91449999, 1.09537627],
       [1.19110908, 1.75570781, 2.66460597, 1.37802603, 2.25498281],
       [1.6403306 , 1.32916413, 2.51984963, 1.24314118, 2.17733149],
       [2.47104419, 2.30029574, 2.54653762, 2.06964797, 1.71652877]])

In [32]:
arr

array([[0.43399678, 0.58672569, 0.08744766, 0.87590884, 0.06218873],
       [0.12458303, 0.9321369 , 0.38942429, 0.64945649, 0.09109793],
       [0.17488488, 0.56287209, 0.98005619, 0.32065206, 0.81314235],
       [0.4948978 , 0.28455027, 0.92419923, 0.21764139, 0.77810004],
       [0.90464081, 0.8330377 , 0.93473464, 0.72737853, 0.5403041 ]])

In [33]:
np.log2(arr)

array([[-1.20424376, -0.76924193, -3.51543646, -0.19114737, -4.00720315],
       [-3.00482056, -0.10138623, -1.36058523, -0.62269523, -3.45643799],
       [-2.51552256, -0.82912099, -0.02906363, -1.64091941, -0.29842016],
       [-1.01479745, -1.81324456, -0.11372421, -2.19997515, -0.36197244],
       [-0.14458301, -0.26354631, -0.09737124, -0.45922175, -0.88815648]])

In [38]:
np.sin(arr)

array([[0.4205004 , 0.55363729, 0.08733625, 0.76812575, 0.06214865],
       [0.124261  , 0.80289562, 0.37965587, 0.60475363, 0.09097198],
       [0.17399477, 0.53361739, 0.83052867, 0.31518545, 0.72645024],
       [0.47494172, 0.28072583, 0.79813857, 0.21592726, 0.70192744],
       [0.78620324, 0.73997803, 0.80444147, 0.66491389, 0.51439679]])

In [39]:
np.cos(arr)

array([[0.90729235, 0.83275792, 0.99617889, 0.64029902, 0.9980669 ],
       [0.99224957, 0.59611963, 0.92512779, 0.79641261, 0.99585345],
       [0.98474658, 0.84572601, 0.55697588, 0.9490301 , 0.68721907],
       [0.88001725, 0.959788  , 0.60247391, 0.97640945, 0.71224846],
       [0.61796802, 0.67263104, 0.59403191, 0.74692002, 0.8575523 ]])

In [40]:
np.tan(arr)

array([[0.46346737, 0.6648238 , 0.08767125, 1.19963599, 0.06226902],
       [0.1252316 , 1.34686995, 0.41038209, 0.75934714, 0.09135077],
       [0.1766899 , 0.63095777, 1.49113938, 0.33211323, 1.05708685],
       [0.53969592, 0.29248733, 1.32476869, 0.22114417, 0.98550925],
       [1.27223937, 1.10012472, 1.35420582, 0.89020762, 0.59984306]])

In [41]:
arr

array([[0.43399678, 0.58672569, 0.08744766, 0.87590884, 0.06218873],
       [0.12458303, 0.9321369 , 0.38942429, 0.64945649, 0.09109793],
       [0.17488488, 0.56287209, 0.98005619, 0.32065206, 0.81314235],
       [0.4948978 , 0.28455027, 0.92419923, 0.21764139, 0.77810004],
       [0.90464081, 0.8330377 , 0.93473464, 0.72737853, 0.5403041 ]])

In [42]:
np.sum(arr, axis=1)

array([2.04626769, 2.18669863, 2.85160757, 2.69938873, 3.94009577])

In [43]:
np.min(arr, axis=0)

array([0.12458303, 0.28455027, 0.08744766, 0.21764139, 0.06218873])

In [45]:
np.mean(arr, axis=1)

array([0.40925354, 0.43733973, 0.57032151, 0.53987775, 0.78801915])

In [46]:
np.std(arr)

0.3069416883814233

In [47]:
np.var(arr)

0.0942132000664388

In [48]:
arr[1:,2:4]

array([[0.38942429, 0.64945649],
       [0.98005619, 0.32065206],
       [0.92419923, 0.21764139],
       [0.93473464, 0.72737853]])

In [49]:
np.sort(arr)

array([[0.06218873, 0.08744766, 0.43399678, 0.58672569, 0.87590884],
       [0.09109793, 0.12458303, 0.38942429, 0.64945649, 0.9321369 ],
       [0.17488488, 0.32065206, 0.56287209, 0.81314235, 0.98005619],
       [0.21764139, 0.28455027, 0.4948978 , 0.77810004, 0.92419923],
       [0.5403041 , 0.72737853, 0.8330377 , 0.90464081, 0.93473464]])

In [50]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [51]:
arr1 = np.append(arr,8)
arr1

array([4, 5, 6, 7, 8, 8])

In [52]:
arr2 = np.insert(arr, 0, [1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
arr3 = np.delete(arr2, [1,3])
arr3

array([1, 3, 5, 6, 7, 8])

In [54]:
arrC = arr3.copy()
arrC

array([1, 3, 5, 6, 7, 8])

In [55]:
arr_cat = np.concatenate((arr1,arr2))
print(arr_cat)

[4 5 6 7 8 8 1 2 3 4 5 6 7 8]


In [56]:
cat = np.hstack((arr1,arr2))
cat

array([4, 5, 6, 7, 8, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
arr = np.array([1,2,3,4,5,6,3,4,2,1])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [58]:
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 2 1 1]


In [61]:
#intersection, differentiation, neither
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))
print(np.union1d(arr1, arr2))

[3 4 5]
[1 2 3 4 5 6 7]
